config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations"
  }

  resources :users, :only => [:show] do
    collection do
      get 'search_by_name'
    end
  end
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'welcome#welcome'

  resources :properties do
    collection do
      get 'search_by'
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = User.find(params[:user_id]) rescue nil
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end


  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" style="width: 64px; height: 64px;" src="<%= conversation.receipts.last.receiver.image %>" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <% if user.blank? %>
        <%= f.select(:recipients, [], {}, { multiple: true , class: "select2 form-control" })%>
      <% else %>
        <%= f.select(:recipients, options_for_select([[ user.name, user.id ]], [user.name, user.id]), {}, { multiple: true , class: "select2 form-control" })%>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

<script>
$.ajaxPrefilter(function (options, originalOptions, jqXHR) {
  if (options.cache) {
    var processResults = originalOptions.processResults;
    var success = originalOptions.success || $.noop,
      url = originalOptions.url;

    var key = originalOptions.url + "#" + originalOptions.data.name
    options.cache = false; //remove jQuery cache as we have our own localStorage
    options.beforeSend = function () {
      if (localStorage.getItem(key)) {
        success(JSON.parse(localStorage.getItem(key)));
      }
    };
    options.success = function (data, textStatus) {
      localStorage.setItem(key, JSON.stringify(data));
      setTimeout(function(){
        localStorage.removeItem(key);
      }, 300);
      if ($.isFunction(success)) {
        success(data); //call back to original ajax call
      }
    };
  }
});
  $('select.select2').select2({
    ajax: {
      delay: 250,
      url: "<%= search_by_name_users_path %>",
      dataType: 'json',
      cache: true,
      data: function (params) {
        return {
          name: params.term // search term
        };
      },
      processResults: function (data) {
        jsonData = JSON.parse(data.users);
        var i, pdata = [];
        for (i=0; i<jsonData.length; i++) {
          pdata.push({id: jsonData[i].id, text: jsonData[i].name});
        }
        return {
          results: pdata
        };
      }
    }
  });

</script>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <a href="#">
          <img class="media-object" style="width: 64px; height: 64px;" src="<%= message.sender.image %>" alt="...">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true, user: @user } %>

app/views/conversations/show.html.erb
<div class="container">
  <h2>Conversation</h2>
  <!-- deprecated (buttons may go here)
  <div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
  </div>
  <div class="col-md-6 text-right">
  </div>
  </div>

  -->
  <div class="row">
    <div class="spacer"></div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render 'mailbox/folders' %>
          <br />
          <%= link_to "Compose", new_conversation_path, class: "btn btn-orange" %>
        </div>
      </div>
    </div>

    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render partial: 'messages' %>
        </div>
        <div class="panel-footer">
          <!-- Reply Form -->
          <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-orange pull-right' %>
          <% end %>
          <div class="clearfix"></div>
        </div>
      </div>
      <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
      <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
          data: {confirm: 'Are you sure?'} %>
      <% end %>
    </div>

  </div>
</div>