config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations"
  }

  resources :users, :only => [:show] do
    collection do
      get 'search_by_name'
    end
  end
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'welcome#welcome'

  resources :properties do
    collection do
      get 'search_by'
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  has_many :property_pictures
  accepts_nested_attributes_for :property_pictures

  validates :city,:address, presence: true
  validates :address,length: {maximum: 55}
  def self.search_by filter
    filter = process_filter(filter)
    query = ""
    option = {}
    if filter[:city].blank?
      return []
    else
      option[:city] = filter[:city]
      query += "city = :city "
    end
    if !filter[:type].blank?
      option[:type] = filter[:type]
      query += "AND type IN :type"
    end
    if !filter[:min_area].blank?
      option[:min_area] = filter[:min_area]
      query += "AND area >= :min_area "
    end
    if !filter[:max_area].blank?
      option[:max_area] = filter[:max_area]
      query += "AND area <= :max_area "
    end
    if !filter[:min_rent].blank?
      option[:min_rent] = filter[:min_rent]
      query += "AND rent >= :min_rent "
    end
    if !filter[:max_rent].blank?
      option[:max_rent] = filter[:max_rent]
      query += "AND rent <= :max_rent "
    end
    if !filter[:period_start].blank?
      option[:period_start] = DateTime.parse(filter[:period_start])
      query += "AND period_start <= :period_start "
    end
    if !filter[:period_end].blank?
      option[:period_end] = DateTime.parse(filter[:period_end])
      query += "AND period_end >= :period_end "
    end
    if !filter[:guest].blank?
      option[:guest] = filter[:guest]
      query += "AND guest >= :guest "
    end
    if !filter[:address].blank?
      option[:address] = "%#{filter[:address]}%"
      query += "AND address LIKE :address"
    end

    properties = Property.where(query,option)
  end

  private

  def self.process_filter filter
    set = ["select","update","delete","create"]
    if set.any? { |op| filter =~ /#{op}/i }
      return ""
    else
      return filter.symbolize_keys
    end
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :create
  before_action :authenticate_user!, :only => [:edit, :update, :create]

  def index
    @city = params[:city]||session[:city]
    session[:city] = @city
    @view = params[:view] || "grid"
    respond_to do |format|
      format.html
      format.js {
        @properties = Property.search_by(city: @city).order("created_at DESC").paginate(:per_page => APP_CONFIG["pagination"]["per_page"], :page => params[:page])
        #paginate
      }
    end
  end

  def new
    respond_to do |format|
      format.html
    end
  end

  def edit
    @property = Property.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def create
    property = current_user.properties.new(property_params)
    if property.save
      #nested attributes ???? WTF !!!!
      unless params[:property_pictures].blank?
        params[:property_pictures]['picture'].each do |a|
          property_picture = property.property_pictures.create!(:picture => a)
        end
      end
      respond_to do |format|
        format.js {
          render :js => "window.location = '#{edit_property_path(property)}'"
        }
        format.html {
          redirect_to property
        }
      end
    else
      respond_to do |format|
        format.js {
        }
      end
    end
  end

  def update
    @property = Property.find(params[:id])
    if @property.update_attributes(property_params)
      #nested attributes ???? WTF !!!!
      unless params[:property_pictures].blank?
        @property.property_pictures.destroy_all
        params[:property_pictures]['picture'].each do |a|
          property_picture = @property.property_pictures.create!(:picture => a)
        end
      end
      respond_to do |format|
        format.html {
          redirect_to @property
        }
      end
    else
      respond_to do |format|
        format.html {
          render 'edit'
        }
      end
    end
  end

  def search_by
    @city = params[:city]||session[:city]
    respond_to do |format|
      format.js {
        # processing here
        params[:filter][:city] = @city
        params[:filter].each {|key,val| params[:filter].delete(key) if params[:filter][key].empty?}
        @properties = Property.search_by(params[:filter])
        #.paginate(:per_page => APP_CONFIG["pagination"]["per_page"], :page => params[:page]) rescue []
        #paginate
      }
    end
  end

  def show
    @property = Property.find(params[:id])
    @property_pictures = @property.property_pictures
    @user = @property.user
    @city = cache_cities(true).select{|m| m['name'].downcase == @property.city.downcase}.first
  end

  private

  def property_params
    # params.require(:property).permit!
    unless params[:property].blank?
      params.require(:property).permit(
        :user_id,
        :property_type,
        :area,
        :rent,
        :period_start,
        :period_end,
        :country,
        :city,
        :address,
        :description,
        :quantity,
        property_pictures_attributes: PropertyPicture.attribute_names.collect { |att| att.to_sym}
      )
    end
  end

  end

app/views/properties/_long_form.html.erb
<%= form_for(property, html: {class: "form pp-form pp-form-long"}) do |f| %>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :city,"City" %>
      <%= f.text_field :city,class: "typeahead tt-input",placeholder: "Helsinki" %>
    </div>
    <div class="col-md-6 form-group">
      <%= f.label :property_type,"Type" %>
      <%= f.select :property_type,["Shared Appartment","Studio","Private","Single Room"],{},class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 form-group">
      <%= f.label :address,"Your room address" %>
      <%= f.text_field :address,class: "form-control long location-address-input",placeholder: "123 Maapitidee 5"%>
    </div>
    <div class="col-md-4 form-group">
      <%= f.label :area,"Total area" %>
      <div class="input-group">
        <%= f.number_field :area,class: "form-control long",placeholder: "12"%>
        <span class="input-group-addon">m2</span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 form-group">
      <%= f.label :period_start,"Start date" %>
      <%= f.text_field :period_start,class: "form-control timepicker" %>
    </div>
    <div class="col-md-3 form-group">
      <%= f.label :period_end,"End date" %>
      <%= f.text_field :period_end,class: "form-control timepicker" %>
    </div>
    <div class="col-md-3 form-group">
      <%= f.label :rent,"Rent" %>
      <div class="input-group">
        <span class="input-group-addon">€</span>
        <%= f.text_field :rent,class: "form-control number-format" %>
      </div>
    </div>
    <div class="col-md-3 form-group">
      <%= f.label :quantity,"Per" %>
      <%= f.select :quantity,["Day","Month","All"],{},class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :description,"Description" %>
      <%= f.text_area :description,class: "form-control",rows: "5",placeholder: "Some basic information about your place" %>
    </div>
    <div class="col-md-6 form-group">
      <%= f.label :pictures %><br>
      <%= f.fields_for :property_pictures do |p| %>
        <div class="field">
          <%= p.file_field :picture, :multiple => true, name: "property_pictures[picture][]", onchange: "readURL(this)", id: "property_property_pictures_attributes", style: "visibility: hidden; height: 0;"%>
        </div>
      <% end %>
      <div class="property-pictures add-new" onclick="$('#property_property_pictures_attributes').click()">
        <i class="glyphicon glyphicon-plus"></i>
      </div>
      <div class="property-pictures preview">
        <div class="preview-container"></div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= f.submit "#{property.id.blank? == true ? 'Post My Place' : 'Update My Place'}",class: "main-orange-btn btn-lg btn-block #{current_user.nil? == true ? 'required-login' : ''}" %>
    </div>
  </div>
<% end %>


<script>
  var hello = <%=raw cache_cities.map{|m| m['name']}.to_json %>;
  var substringMatcher = function(strs) {
    return function findMatches(q, cb) {
      var matches, substringRegex;
      matches = [];
      substrRegex = new RegExp(q, 'i');
      $.each(strs, function(i, str) {
        if (substrRegex.test(str)) {
          matches.push(str);
        }
      });

      cb(matches);
    };
  };
   $('.pp-form-long .typeahead').typeahead({
    hint: true,
    highlight: true,
    minLength: 1
  },
  {
    name: 'hello',
    source: substringMatcher(hello)
  })
  var startPeriod = new Date();
  $(function () {
    $('.pp-form-long .timepicker').datepicker( {
      orientation: "top auto",
      format: "yyyy-mm-dd",
      autoclose: true,
      weekStart: 1,
      startDate: startPeriod
    }).on('changeDate', function(ev) {

    }).on('hide', function(event) {
      event.preventDefault();
      event.stopPropagation();
      return false;
    }).click(function(e) {
       e.preventDefault();
       e.stopPropagation();
    })
  });
$(document).ready(function() {
  $('#new_property.pp-form-long').sisyphus({
    excludeFields: $("input[type=file]"),
    customKeySuffix: "",
    locationBased: false,
    timeout: 0,
    autoRelease: true,
    onSave: function() {},
    onBeforeRestore: function() {},
    onRestore: function() {},
    onRelease: function() {}
  });
});
$(".pp-form-long #property_address").maxlength({
  threshold: 10
});

</script>

app/views/properties/_properties.html.erb
<%  properties.each do |property| %>
  <%= render partial: "properties/property",locals: {property: property} %>
<% end %>

app/views/properties/_property.html.erb
<% cache property do %>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="pin" onclick='window.open("<%= property_path(property) %>")'>
      <div class="fluid-thumbnail-grid-image-title">
        <% if property.property_pictures.empty? %>
          <img src="<%= image_path('thumbnail-default.jpg') %>" />
        <% else %>
          <img src="<%= property.property_pictures.first.picture.thumb.url %>" />
        <% end %>
        <div class="title">
          <%= property.property_type %>
        </div>
        <div class="price">
          € <%= property.rent %> / <%= property.quantity %>
      </div>
      </div>
      <div class="fluid-relative description">
        <div class="pp-details">
          <strong class="org-st" style="color: #337ab7">
            <%= property.period_start.strftime("%D") %> - <%= property.period_end.strftime("%D") %>
          </strong>
          <br/>
          <%= property.address %>, <%= property.city %>, <%= property.country %>
        </div>
        <div class="clear clearfix"> </div>
      </div>
    </div>
  </div>
<% end %>

app/views/properties/edit.html.erb
<div class="main-content" style="max-width: 928px">
  <div class="pp-title">
    <h1> Finish it </h1>
  </div>
  <div class="form-wrapper">
    <% @property.property_pictures.build if @property.property_pictures.empty? %>
    <%= render partial: "properties/long_form",locals: {property: @property} %>
  </div>
</div>

app/views/properties/index.html.erb
<%= render partial: 'shared/mkpl_small_with_search', locals: { city: @city, description: "The awesome city" } %>

<div class="container">

  <!-- top bar -->
  <div class="home-toolbar clear clearfix">
    <!-- button group to switch views -->
    <div class="filters-enabled home-toolbar-button-group">
      <a href="javascript:window.history.pushState('properties-grid', '', '/properties?city=<%= @city %>&view=grid');" class="home-toolbar-button-group-button <%= @view == "grid" ? "selected" : ""%>" title="grid">
        <i class="glyphicon glyphicon-th-large"></i>
        <span class="home-toolbar-button-text">
          Grid
        </span>
      </a>
      <a href="javascript:window.history.pushState('properties-grid', '', '/properties?city=<%= @city %>&view=list');" class="home-toolbar-button-group-button <%= @view == "list" ? "selected" : ""%>" title="list">
        <i class="glyphicon glyphicon-th-list"></i>
        <span class="home-toolbar-button-text">
          List
        </span>
      </a>
      <a href="/properties?city=<%= @city %>&view=map" class="home-toolbar-button-group-button <%= @view == "map" ? "selected" : ""%>" title="map">
        <i class="glyphicon glyphicon-globe"></i>
        <span class="home-toolbar-button-text">
          Map
        </span>
      </a>
    </div>

    <!-- Dropdown
    <div class="home-toolbar-filters home-toolbar-filters-mobile-hidden" id="home-toolbar-filters">
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sort by <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="">Sort by Price</a></li>
          <li><a href="#">Sort by Posted Date</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Sort by Type</a></li>
        </ul>
      </div>
    </div>
    -->
  </div>

  <!-- left column for filters -->
  <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 pp-filters">
    <h4> <i class="glyphicon glyphicon-search"></i> Search terms</h4>
    <div class="filter-wrapper ">
      <a class="btn btn-sm btn-default pull-right" href="<%= properties_path(city: @city,reset: true) %>" data-remote="true" onclick="reset_filter()"> X </a>
      <%= form_tag(search_by_properties_path,method: :get,remote: true,id: "pp-filter") do %>
        <div class="filter" id="price-filter" style="padding-top: 10px;">
          <label for="price">Price range:</label>
          <input type="text" id="pp-price-input" readonly style="border:0; color:#f6931f; font-weight:bold;" class="slider-input">
          <input type="hidden" id="hidden-pp-min-price" name="filter[min_rent]" readonly >
          <input type="hidden" id="hidden-pp-max-price" name="filter[max_rent]" readonly >
          <div id="price-range"></div>
        </div>
        <div class="filter" id="area-filter">
          <label for="price">Area range:</label>
          <input type="text" id="pp-area-input" readonly style="border:0; color:#f6931f; font-weight:bold;"  class="slider-input">
          <input type="hidden" id="hidden-pp-min-area" name="filter[min_area]" >
          <input type="hidden" id="hidden-pp-max-area" name="filter[max_area]" >
          <div id="area-range"></div>
        </div>
        <div class="filter" id="max-filter">
          <label for="price">Max Person:</label>
          <input type="text" id="pp-max-input" name="filter[guest]" readonly style="border:0; color:#f6931f; font-weight:bold;"  class="slider-input">
          <div id="max-range"></div>
        </div>
        <div class="filter" id="date-filter" style="margin-bottom: 0px;">
          <div class="row">
            <div class="form-group col-md-6 col-xs-6 col-sm-6">
              <label for="start_period"> Start </label>
              <input type="text" id="start_period" name="filter[period_start]" class="form-control start-time timepicker">
            </div>
            <div class="form-group col-md-6 col-xs-6 col-sm-6">
              <label for="end_period"> End </label>
              <input type="text" id="end_period" name="filter[period_end]" class="form-control end-time timepicker">
            </div>
          </div>
        </div>
        <div class="filter" id="address filter">
          <div class="form-group">
            <label for="address"> Address </label>
            <input type="text" id="address" name="filter[address]" class="form-control" placeholder="E.g: Maapadontie 5">
          </div>
        </div>
        <div class="form-group">
          <button class="btn btn-block btn-warning"> Search </button>
        </div>
      <% end %>
    </div>
  </div>
  <!-- right column for results -->
  <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
    <div id="wrapper">

      <!-- list/grid view -->
      <div id="pp-holder-wrapper" class="row">
        <div id="pp-holder" class="<%= @view %> unload">
          <i class='fa fa-spinner fa-spin'></i>
        </div>
      </div>
      <!-- list/grid view end -->
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $.ajax({
      type: "GET",
      dataType: "script",
      url: "<%= properties_path %>",
      data: {city: "<%= @city %>"},
      success: function() {
        if($(".pagination").length != 0)
          $("#pp-holder-wrapper").append("<div ><button class='btn btn-primary btn-block' id='nxt-btn' onclick='next_page()'> <i class='glyphicon glyphicon-triangle-bottom'></i> </button></div>");
       // $(window).scroll(function() {
       //   if($(window).scrollTop() + $(window).height() > $(document).height() - .75*$(document).height()) {
       //     next_page();
       //   }
       // });
      }
    })
    $("#pp-filter").submit(function() {
      $("#pp-holder").html("<i class='fa fa-spinner fa-spin'></i>");
    })
    $('.home-toolbar-button-group > a').click(function(){
      $(this).addClass('selected');
      $(this).siblings().removeClass('selected');
      $('#pp-holder')[0].className = $(this).attr('title');
    })
    $(function() {
      $( "#price-range" ).slider({
        range: true,
        min: 10,
        max: 1000,
        values: [ 10, 1000 ],
        step: 10,
        slide: function( event, ui ) {
          $( "#pp-price-input" ).val( "€" + ui.values[ 0 ] + " - €" + ui.values[ 1 ] );
          $("#hidden-pp-min-price").val(ui.values[0]);
          $("#hidden-pp-max-price").val(ui.values[1]);
        }
      });
      $( "#pp-price-input" ).val( "€" + $( "#price-range" ).slider( "values", 0 ) +
        " - €" + $( "#price-range" ).slider( "values", 1 ) );
      $("#hidden-pp-min-price").val($( "#price-range" ).slider( "values", 0 ) );
      $("#hidden-pp-max-price").val($( "#price-range" ).slider( "values", 1 ) );
    });
    $(function() {
      $( "#area-range" ).slider({
        range: true,
        min: 0,
        max: 100,
        values: [ 10, 100 ],
        step: 5,
        slide: function( event, ui ) {
          $( "#pp-area-input" ).val(ui.values[ 0 ] + " - " + ui.values[ 1 ] + " m2");
          $("#hidden-pp-min-area").val(ui.values[0]);
          $("#hidden-pp-max-area").val(ui.values[1]);
        }
      });
      $( "#pp-area-input" ).val( $( "#area-range" ).slider( "values", 0 ) +
        " - " + $( "#area-range" ).slider( "values", 1 ) + " m2");
      $("#hidden-pp-min-area").val($( "#area-range" ).slider( "values", 0 ) );
      $("#hidden-pp-max-area").val($( "#area-range" ).slider( "values", 1 ) );
    });
    $(function() {
      $( "#max-range" ).slider({
        range: "min",
        value: 1,
        min: 1,
        max: 10,
        step: 1,
        slide: function( event, ui ) {
          $( "#pp-max-input" ).val( ui.value );
        }
      });
      $( "#pp-max-input" ).val($( "#max-range" ).slider( "value" ) );
    });
  })
  var next_page = function() {
    $(".pagination .next_page").click();
  };
  var reset_filter = function() {
    $("#price-range").slider("values",[10,1000]);
    $("#hidden-pp-max-price").val(1000);
    $("#hidden-pp-min-price").val(10);
    $("#pp-price-input").val( "€" + 10 + " - €" + 1000);

    $("#area-range").slider("values",[10,100]);
    $("#hidden-pp-max-area").val(10);
    $("#hidden-pp-min-area").val(100);
    $("#pp-area-input").val(10 + " - " + 100 + " m2");

    $("#max-range").slider("value",1);
    $("#pp-max-input").val(1);
  }
</script>

app/views/properties/index.js.erb
if($("#pp-holder").hasClass("unload")) {
  $("#pp-holder").removeClass("unload");
  $("#pp-holder").html("");
}
$("#pp-holder").siblings('.pagination').remove();
$("#pp-holder").parent().append("<%=j js_will_paginate @properties %>");
if($('.pagination .next_page.disabled').length == 1 || $('.pagination').length == 0) {
  $("#nxt-btn").remove();
}
<% if params[:reset] %>
  $("#pp-holder").html("");
<% end %>
$("#pp-holder").append("<%=j render partial: 'properties',locals: {properties: @properties} %>");

app/views/properties/new.html.erb
<div class="main-content" style="max-width: 928px">
  <div class="pp-title">
    <h1> Finish it </h1>
  </div>
  <div class="form-wrapper">
    <% property = Property.new %>
    <% property.property_pictures.build %>
    <%= render partial: "properties/long_form",locals: {property: property } %>
  </div>
</div>

app/views/properties/show.html.erb
<div class="mkpl-lander">
  <div class="cover-img">
    <figure class="mkpl-cover-small fluidratio"></figure>
    <div class="cover-img-fade">
      <figure class="mkpl-cover-small-fade fluidratio"></figure>
    </div>
  </div>
  <div class='title-content'>
    <div class="title-wrapper">
      <div class="title-header">
        <h1>
          <%= "#{@property.address}, #{@property.city}" %>
          <span> <i class="glyphicon glyphicon-home"></i> <%= @property.property_type %></span>
        </h1>
      </div>
    </div>
  </div>
</div>
<article class="main-page-content">

  <div class="main-content">
    <div class="back-link">
      <%= link_to properties_path(city: @city['name']) do %>
        <i class="glyphicon glyphicon-triangle-left"></i> Back to search results in <strong> <%= "#{@city['name']}" %></strong>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-8">
        <div class="qt-row" id="img-cs-wrapper">
          <div id="carousel-generic" class="carousel slide" data-interval="false">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <% @property_pictures.each_with_index do |pp, index| %>
                <li data-target="#carousel-generic" data-slide-to="<%= index+1 %>" class="<%= index == 0 ? "active" : "" %>"></li>
              <% end %>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
              <% @property_pictures.each_with_index do |pp, index| %>
                <div class="item <%= index == 0 ? "active" : "" %>">
                  <img src="<%= pp.picture.url %>" alt="<%= index+1 %>">
                </div>
              <% end %>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-generic" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-generic" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
        <div class="qt-row" id="description-wrapper">
          <p>
            <strong> Area: <%= @property.area %> m2 </strong>
          </p>
          <p>
            <%= @property.description %>
          </p>
        </div>
        <div class="qt-row" id="created-at-wrapper">
          <strong>
            <i class="glyphicon glyphicon-calendar"></i>
            <span> Listing created at <%= @property.created_at.strftime("%d %B %Y") %> </span>
        </div>
        <div class="qt-row clear clearfix" id="social-wrapper">
          <div class="social-btn" id="fb-btn-wrapper">
            <div class="fb-share-button" data-href='<%= "#{request.protocol}#{request.host_with_port}#{request.fullpath}" %>' data-layout="button_count"></div>
          </div>
          <div class="social-btn" id="tw-btn-wrapper">
            <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
          </div>
        </div>
      </div>

      <!-- SIDEBAR -->
      <div class="col-md-4">
        <div class="qt-row">
          <div class='price clear clearfix'>
            <span class="price-amount"> € <%= @property.rent %> </span>
            <span class="price-pp"> <%= @property.quantity == "all" ? "all" : "per #{@property.quantity}" %> </span>
          </div>
        </div>

        <div class="qt-row row-dd">
          <form >
            <div class="qt-link">
              <div class="qt-wrapper clear clearfix">
                <strong>
                  <i class="glyphicon glyphicon-calendar"></i>
                  <span> Available from </span>
                </strong>
                <h4 style="font-size: 18px;margin: 10px 0px 10px 0px;">
                  <p style="margin-bottom: 5px;"><span class="qt-period"><%= "#{@property.period_start.strftime("%d %B %Y")}" %> </span></p>
                  <p><strong style="font-size: 14px;margin: 0px 5px"> to </strong></p>
                  <p><span class="qt-period"><%= "#{@property.period_end.strftime("%d %B %Y")}" %></span></p>
                </h4>
              </div>
              <% if false %>
              <%# if @property.quantity != "all" %>
              <div class="qt-wrapper clear clearfix">
                <label for="pp-qq"> Number of <%=@property.quantity %>s: </label>
                <div class="qt-input">
                  <input id="quantity" min="1" name="quantity" placeholder="Quantity" step="1" type="number" value="1">
                </div>
              </div>
              <% end%>
            </div>
            <% unless @user.nil? %>
            <div class="qt-btn">
              <% if @user == current_user %>
                <a href="<%= edit_property_path(@property) %>" type="button" class="btn btn-lg btn-block btn-warning"> Edit </a>
              <% elsif @user %>
                <a href="<%= new_conversation_path %>?user_id=<%= @user.id %>" type="button" class="btn btn-lg btn-block btn-warning <%= current_user.nil? == true ? 'required-login' : ''  %>"> Contact </a>
              <% end %>
            </div>
            <% end %>
          </form>
        </div>

        <% unless @user.nil? %>
        <div class="qt-row row-dd">
          <div class="qt-owner">
            <div class="qt-owner-ava">
              <a href="<%= current_user == @user ? edit_user_registration_path(@user) : user_path(@user)  %>">
                <img alt="Open-uri20150706-11-1d0eer6?1436204991" class="owner-avatar-image" src="<%= @user.image %>">
              </a>
            </div>
            <div class="qt-owner-details">
              <div class="owner-name">
                <a href="<%= current_user == @user ? edit_user_registration_path(@user) : user_path(@user)  %>" class="owner-name-link"><%= @user.name %></a>
              </div>
              <div class="owner-contact">
                <% addr = "#{@user.street_addr} #{@user.city} #{@user.country}"  %>
                <span><%= addr.blank? == true ? "N/A" : addr %></span>
              </div>
            </div>
          </div>
        </div>
        <% end %>

        <div class="qt-row">
          <!-- GOOGLE MAP -->
          <div style='width: 100%'>
            <div id="map" style='width: 100%; height: 200px;'></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</article>

<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @city['latitude'] %>,
      "lng": <%= @city['longitude'] %>,
      "infowindow": "I'm here!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(14);
});

</script>