config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations"
  }

  resources :users, :only => [:show] do
    collection do
      get 'search_by_name'
    end
  end
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'welcome#welcome'

  resources :properties do
    collection do
      get 'search_by'
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end

end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/views/mailbox/_folder_view.html.erb
<div class="mkpl-lander">
  <div class="cover-img">
    <figure class="mkpl-cover-small fluidratio"></figure>
    <div class="cover-img-fade">
      <figure class="mkpl-cover-small-fade fluidratio"></figure>
    </div>
  </div>
  <div class='title-content'>
    <div class="title-wrapper">
      <div class="title-header">
        <h1>
          Mailbox
        </h1>
      </div>
    </div>
  </div>
</div>
<div class="container mailbox">
  <br />
  <div class="row">
    <div class="spacer"></div>
    <div class="col-md-12">
      <!-- we'll configure this to compose new conversations later -->
      <div class="spacer"></div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render 'mailbox/folders' %>
          <br />
          <%= link_to "Compose", new_conversation_path, class: "btn btn-orange" %>
        </div>
      </div>
    </div>

    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
          <% if is_conversation %>
            <%= render partial: 'conversations/form', locals: { user: user }  %>
          <% else %>
            <%= render partial: 'conversations/conversation', collection: messages %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Trash</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>