config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations"
  }

  resources :users, :only => [:show] do
    collection do
      get 'search_by_name'
    end
  end
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'welcome#welcome'

  resources :properties do
    collection do
      get 'search_by'
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

end

app/views/layouts/_brand.html.erb
<div class="nav dropdown pull-left">
  <a class="dropdown-toggle navbar-brand" data-toggle="dropdown" href="#">
    Sublease <strong class="org-st"> in</strong> Finland
  </a>
  <ul class="dropdown-menu">
    <li><a href="<%= properties_path(city: session[:city])%>">Search results in <strong class="org-st"><%= session[:city] %> </strong></a></li>
    <li><a href="/">City select</a></li>
  </ul>
</div>

app/views/layouts/_header.html.erb
<header>
  <%= nav_bar static: :top,brand: "", responsive: true do %>
  <%= menu_group pull: :right do %>
    <% if current_user %>
      <%= menu_item mailbox_inbox_path,"",class: "topbar-link topbar-link-ontop" do %>
        <i class="inbox-ico glyphicon glyphicon-envelope"></i> Inbox
      <% end %>
      <%= drop_down "Menu" do %>
        <%= menu_item edit_user_registration_path,"",class: "topbar-link" do%>
          <i class="glyphicon glyphicon-user"></i> Profile
        <% end %>
        <%= drop_down_divider %>
        <%= menu_item destroy_user_session_path,"", class: "topbar-link" do %>
          <i class="glyphicon glyphicon-log-out"></i> Sign Out
        <% end %>
      <% end %>
    <% else %>
      <%= menu_item "Register", 'javascript:;', "data-toggle" => "modal", "data-target" => "#loginModal","class" =>  "topbar-link topbar-link-ontop dsk-link"%>
      <%= menu_item "Sign In", 'javascript:;', "data-toggle" => "modal", "data-target" => "#loginModal","class" =>  "topbar-link  topbar-link-ontop dsk-link"%>
      <%= menu_item "Register", new_user_session_path,"class" =>  "btn btn-default mobile-link","style" => "margin-left: 15px;margin-bottom: 10px;width: 80%"%>
      <%= menu_item "Sign In", new_user_session_path,"class" =>  "btn btn-default mobile-link","style" => "margin-left: 15px;margin-bottom: 10px;width: 80%"%>
      <%= menu_item "Post Place for FREE", new_property_path, "class" =>  "btn btn-warning mobile-link","style" => "color: white;margin-left: 15px;margin-bottom: 10px;width: 80%"%>
    <% end %>
   <!-- Single button -->
   <%= menu_item do %>
      <div class="dsk-link dropdown keep-open pp-dropdown">
        <button type="button" class="btn btn-warning pp-dropdown-toggle" aria-haspopup="true" aria-expanded="false">
          Post your place <strong> FREE !! </strong> <span class="caret"></span>
        </button>
        <div class="dropdown-menu keep-open pp-dropdown-menu">
          <%= render partial: "properties/short_form",locals: {property: Property.new} %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>
</header>

<%= render partial: 'devise/sessions/modal_login' %>

<script>
  $(".navbar-brand").remove();
  $(".navbar-header").prepend("<%=j render partial: 'layouts/brand' %>");
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sublease in Finland</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
  <script>
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.4&appId=1463680153931394";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
</head>
<body>
<%= render partial: 'layouts/header' %>
<div id="fb-root"></div>

<% flash.each do |key, value| %>
    <div class="text-center <%= flash_class(key) %>">
      <%= value %>
    </div>
<% end %>

<%= yield %>

</body>
<script>
  $(document).ready(function() {
    fixbs();
    $(".dropdown-toggle").dropdown();
    $('.required-login').click(function(e){
      e.preventDefault();
      $('#loginModal').modal('show');
    });
  });
  $(".location-address-input").geocomplete({
    componentRestrictions: {country: 'fi'}
  })
</script>
</html>

app/views/layouts/welcome_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sublease in Finland</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>